channel_sources:
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main
rust_compiler_version:
  - 1.78.0
c_compiler:
  - clang  # [win]
c_compiler_version:
  - 17  # [win]
c_stdlib_version:        
  - 10.12  # [osx and x86_64]
