{% set name = "polars" %}
{% set version = "0.19.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars-{{ version }}.tar.gz
    sha256: 7ba32d104832fed1ac75b8f264f11953751edf062b2ab9d4e69b19ab5a224a0c

build:
  number: 0
  skip: true  # [win and python_impl=="pypy"]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not (build_platform == "linux-64" and target_platform == "win-64")]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.1,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - {{ compiler('rust') }}
    - ninja                               # [build_platform == "linux-64" and target_platform == "win-64"]
    - pkg-config                          # [build_platform == "linux-64" and target_platform == "win-64"]
    - posix                               # [win and not (build_platform == "linux-64" and target_platform == "win-64")]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    # this is a hacky way to do cross-compilation from linux to windows
    - python              # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - pip                 # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - maturin >=1.2.1,<2  # [not (build_platform == "linux-64" and target_platform == "win-64")]
  run:
    - python
    - numpy >=1.16.0
    - backports.zoneinfo                   # [py<39]
    - typing_extensions >=4.0.0            # [py<311]
    - packaging                            # [py>=310]

test:
  imports:
    - polars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - '0xbe7a'
